name: ARM TTK

on: 
  push:
    branches: master
    paths: 
      - ".github/workflows/ARM-TTK.yml"
jobs:
   # JOB to run ARM Test Toolkit for arm templates
  test-arm-template-1:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout source code
         uses: actions/checkout@v2.3.3

       - name: Run Test ARM Templates
         id: pathtest

         uses: aliencube/arm-ttk-actions@v0.3
         with:
            path: ./templates
            files: basicLogicApp.json
            
       - name: Test ARM Results
         shell: bash
         continue-on-error: false
         run: |
           echo ${{steps.pathtest.outputs.results}}

