name: Pre-Deployment Check

env:
  TEMPLATE: './templates/mainTemplate.json'

on: 
  pull_request:
    types: [opened]
  push:
    branches: master

jobs:

  test-arm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.3
        
      - name: Test ARM Templates - path
        id: pathtest
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: ${{env.TEMPLATE}}
