name: Pre-Deployment Check

env: 
  ENV_FILE: ./POC/config.env 

    
on: 
  pull_request:
    types: [opened, edited, reopened]
    
  push:
    branches: master
    paths: 
      - ".github/workflows/PreDeployment.yml"
    
jobs:
  GetEnvFile:
    runs-on: ubuntu-latest
    steps:
      - name: GetEnvStep
      - uses: actions/checkout@v2
      - run: |
         while vars= read -r line; do
              echo "Text read from file: $line"
              echo ::set-env name=$line
          done < ${{env.ENV_FILE}}
