name: Pre-Deployment Check

# env:
#   TEMPLATE: './templates/mainTemplate.json'

on: 
  pull_request:
    types: [opened, edited, reopened]
    
  push:
    branches: master
    paths: 
      #- ".github/workflows/PreDeployment.yml"
      - "templates/**"
      - "src/**"
    
jobs:

#   security:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - name: Run Snyk to check for vulnerabilities
#       uses: snyk/actions/dotnet@master
#       env:
#         SNYK_TOKEN: eb0f42c4-3fa2-4c51-9141-f43cc613d0c6

# JOB to run change detection
  changes:
    name: Identify Changes
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      templates : ${{ steps.filter.outputs.templates }}
      src: ${{ steps.filter.outputs.src }}
      templates_files: ${{ steps.filter.outputs.templates_files }}
      src_files: ${{ steps.filter.outputs.src_files}}
    steps:
    # For pull requests it's not necessary to checkout the code
    - name: Checkout source code
      uses: actions/checkout@v2.3.3
      
    - uses: dorny/paths-filter@v2
      id: filter
      
      with:
        list-files: json
        filters: |
          templates:
            - 'templates/**'
          src:
            - 'src/**'
 
    - name: Changed template files
      shell: bash
      run: |
          echo ${{ steps.filter.output.templates_files }}
          
    - name: Changed src files
      shell: bash
      run: |
          echo ${{ steps.filter.outputs.src_files }}

 # JOB to run codeql scan for code analysis
  codeql-analysis:
    name: codeql-analysis
    needs: changes
    # Run code-analysis job only if changes are there in src path
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [csharp]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.3
      with:
        fetch-depth: 2
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
              
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      
 # JOB to run ARM Test Toolkit for arm templates
  test-arm-template:
    needs: changes
    # Run test-arm-template job only if changes are there in templates path
    if: ${{ needs.changes.outputs.templates == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.3
        
      - name: Run Test ARM Templates
        id: pathtest
        
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: ./templates #${{ needs.changes.outputs.templates_files}}
              
      - name: Test ARM Results
        shell: bash
        continue-on-error: false
        run: |
          echo ${{steps.pathtest.outputs.results}}
