name: Pre-Deployment Check

# env:
#   TEMPLATE: './templates/mainTemplate.json'

on: 
  pull_request:
    types: [opened]

  push:
    branches: master
    paths: './github/workflows/PreDeployment.yml'
    
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/dotnet@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
