name: Pre-Deployment Check

env: 
  ENV_FILE: ./POC/config.env 

on:    
  push:
    paths: 
      - ".github/workflows/PreDeployment.yml"
    
jobs:
  GetEnvFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - run: |
         while vars= read -r line; do
              echo "Text read from file: $line"
              echo ::set-env name=$line
          done < ${{env.ENV_FILE}}
  ShowEnvVars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - run: |
         echo ${{env.ENV_FILE}}
         echo ${{env.APP_NAME}}
